# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  ORGANIZATION_MEMBER: 2

requiredLabels:
- merge
