# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

deleteBranchAfterMerge: true
reportStatus: true
blockingChecks:
- ci/circleci
minApprovals:
  COLLABORATOR: 2

requiredLabels:
- merge
