# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

deleteBranchAfterMerge: true
reportStatus: true

minimumApprovals:
  ORGANIZATION_MEMBER: 1

requiredLabels:
- merge
