# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

deleteBranchAfterMerge: true
reportStatus: true

minimumApprovals:
  ORGANISATION_MEMBER: 2

requiredLabels:
- merge
