# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  ORGANISATION_MEMBER: 1

requiredLabels:
- merge
